
= yaml 格式文件
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

YAML 文件的后缀为 yaml 或 yml.


- 大小写敏感
- key: value  键值对. kv之间有空格, 即在冒号后加空格.
- 使用"缩进"来表示层级关系. 缩进的"空格数量"不重要, 只要相同层级的元素"左对齐"即可.
- 注释, 用 # 来表示
- 字符串无需加引号.   +
加了单引号 '', 字符串会被转义.  +
如果加的是双引号 "", 则字符串不会被转义.

- YAML 支持 : 字典、数组（理解为Python中的列表）、纯量,  三种数据类型

纯量（scalars）：单个的、不可再分的值 +
数组：一组按次序排列的值，又称为列表（list）/ 序列（sequence） +
对象：键值对的集合。又称为映射（mapping）/ 哈希（hashes） / 字典（dictionary） +

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|纯量
|是最基本的，不可再分的值，包括：
字符串
布尔值
整数
浮点数
Null
时间
日期

....
key1: true
....

|-> 字符串
|可不用加单引号或双引号

....
str: 这是一行字符串
# 转为json之后：{ "str": "这是一行字符串" }
....

....
# 字符串可以拆成多行，换行符会被转化成一个空格
str: 这是一段
  多行
  字符串
# 转换为 JSON 格式 { "str": "这是一段 多行 字符串" }
....

单引号会对特殊字符转义，双引号不会对特殊字符转义
....
str1: '这是\n字符串'
str2: "这是\n字符串"
# 转换后的结果 {'str1': '这是\\n字符串', 'str2': '这是\n字符串'}
....

|-> 布尔值
|TRUE  #true,True都可以 +
FALSE  #false，False都可以



|-> 整数型
|1234

|-> 浮点型
|3.14 +
6.8523015e+5  #可以使用科学计数法

|对象
|对象键值对：使用冒号结构表示：key: value，冒号后面要加一个空格。

层级关系有如下两种表示方式:

写法1：
....
key:
  key1: value1
  key2: value2
....

写法2：
....
key: {key1: value1, key2: value2, ...}
....

|数组
|数组/List/Set（用 -值表示数组中的一个元素）

写法1
....
pets:
  - cat
  - dog
  - pig
....

写法2
....
pets: [cat,dog,pig]
....


|===




== 对象的写法

有两种:

行内写法是:
....
k: {k1:v1, k2:v2, k3:v3}
....



