
= 数列
:toc:

---

== 数列

数列:: 数列的一般形式为:
\begin{align}
a_1, a_2, a_3, ... a_n, ...
\end{align}

- 其中 stem:[ a_n ]表示数列的第 n 项. 也称 n 为 stem:[ a_n ]的序号.
- n: 称为数列的"通项".
- 此时, 一般将整个数列, 简记为 stem:[  {a_n}]

通项公式 general formulas :: 如果数列 stem:[  {a_n}] 的第 n 项stem:[  a_n], 与n之间的关系, 可以用一个公式来表示，那么这个公式就叫做数列的 "通项公式"（general formulas）。 显然, 只要知道了某个数列的"通项公式", 就能写出该数列中的任意一项. 这与函数异曲同工, 输入一个x, 输出相应的y ! +
有的数列的通项, 可以用两个或两个以上的式子来表示。 +
没有通项公式的数列也是存在的，比如, 所有质数组成的数列。

.标题
====
例如：某数列的通项公式是 stem:[ b_n = \sin \frac{n \pi}{2} ], 那么该数列中的第 2 项是什么?
即:
\begin{align}
b_2 = \sin \frac{2 \pi}{2} = \sin \pi = 0
\end{align}
====

.标题
====
例如：这个数列: 0, 2, 0, 2, ... 的通项公式是什么?
即:
\begin{align}
a_n = \begin{cases}
0, \quad n为奇数 \\
2, \quad n为偶数
\end{cases}
\end{align}
====

---

== 数列的递推关系

递推公式:: 如果数列 stem:[  {a_n}] 的第n项, 与它前一项或几项的关系, 可以用一个式子来表示，那么这个公式, 就叫做这个数列的"递推公式"。 注意: 递推公式还需要给出首项(或者前几项)的值.

.标题
====
例如：已知 stem:[ a_1 = 1] , stem:[ a_n = 1 + \frac{1}{a_{n-1}} (n \ge 2) ], 写出这个数列的 前5项.

思考: 上面的式子, 给出了 stem:[ a_n ] 和 stem:[ a_{n-1} ] 的关系. 它们是相邻的两项, 所以这个式子, 就是该数列的"递推公式".

显然, 我们只要知道了前面一项 stem:[ a_{n-1} ]的值, 就能通过这个"递推公式", 知道它的后一项, 即 stem:[ a_n ] 的值.

那么我们就来一项项算: 我们让 stem:[a_1 ] 来代表  stem:[ a_{n-1} ] , 则:

\begin{align}
& a_n = 1 + \frac{1}{a_{n-1}} \\
& a_2 = 1 + \frac{1}{a_1} = 1 + \frac{1}{1} = 2 \\
& a_3 = 1 + \frac{1}{a_2} = 1 + \frac{1}{2} = \frac{3}{2} \\
& a_4 = 1 + \frac{1}{a_3} = 1 + \frac{1}{\frac{3}{2}} = \frac{5}{3} \\
& a_5 = 1 + \frac{1}{a_4} = 1 + \frac{1}{\frac{5}{3}} = \frac{8}{5} \\
\end{align}

====

.标题
====
例如：有一个数列stem:[ {a_n} ] , 已知 stem:[ a_1 = 5, \quad a_n = a_{n-1} +3 \quad (n \ge 2)], 那么该数列的前5项是什么?

思考: 从它的递推公式 stem:[  a_n = a_{n-1} +3], 可以看出: stem:[  a_n - a_{n-1} = 3] , 即相邻两项的差是3, 那么结果就简单了: 该数列每项之间相差3.

即它的前 5 项是: 5, 8, 11, 14, 17
====


.标题
====
例如： 写出数列 1, 3, 6, 10, ... 的一个递推公式.

思考: 从上面我们可以知道:
\begin{align}
& a_2 - a_1 = 3-1 = 2 <- 和前一项的序号n一致, 本处即和 a_2 的序号 2 一致 \\
& a_3 - a_2 = 6-3 = 3 <- 和前一项的序号n, 即3 一致\\
& a_4 - a_3 = 10-6 = 4 <- 和前一项的序号n, 即4 一致\\
\end{align}

所以, 该数列的递推公式就是:
\begin{align}
a_n - a_{n-1} = n \quad (n \ge 2), \quad 且 a_1 = 1
\end{align}

====

== 等差数列 Arithmetic progression -> stem:[  a_{n+1} - a_n = d]

等差数列 Arithmetic progression:: 等差数列是指从第二项起，每一项与它的前一项的差, 等于同一个常数. 常用A、P表示。 +
这个常数叫做等差数列的"公差"(Common difference)，公差常用字母 d (difference) 表示。

....
Arithmetic  /əˈrɪθmətɪk/  n. 算术.
progression [ C ] a number of things that come in a series 系列；序列；连续
....

"等差数列"的数学定义, 可以表示为:
\begin{align}
& a_{n+1} - a_n = d \quad (n \in N^*), 其中 d 为常数. \\
& 或 \; a_n - a_{n-1} = d, \quad (n \ge 2)
\end{align}

可以看出, 当:

- 公差d > 0 时, stem:[ {a_n} ] 为 递增数列
- 公差d < 0 时, stem:[ {a_n} ] 为 递减数列
- 公差d = 0 时, stem:[ {a_n} ] 为 常数列

---

== 等差中项 arithmetic mean -> stem:[  M = \frac{a+b}{2}]

等差中项 arithmetic mean:: 若 a, M, b 成 等差数列, 则 M 叫做 a与b 的"等差中项", 且: stem:[ M-a = b - M ], 即: stem:[ 2M = b+a ]
\begin{align}
M = \frac{a+b}{2}
\end{align}


....
mean : ~ (between A and B) a quality, condition, or way of doing sth that is in the middle of two extremes and better than either of them 中间；中庸；折中 /平均数；平均值；算术中项
....

.标题
====
例如： 在 -1, 5 这两个数中间插入一个数, 使这三个数组成一个"等差数列". 即是问这两个数的"等差中项"是什么?

根据"等差中项"的公式:
\begin{align}
M & = \frac{a+b}{2} \\
&  = \frac{-1 +5}{2} = 2
\end{align}

====

---

== "等差数列"的通项公式 -> stem:[ a_n = a_1 +(n-1)d ]

如果已知等差数列 stem:[ {a_n} ] 的首项是 stem:[  a_1], 公差是 d, 那么可以求出该"等差数列"的通项公式吗? 可以.

方法1 (不完全归纳法): 可知:

\begin{align}
& a_2 = a_1 + d \\
& a_3 = a_2 + d  =  a_1 + 2d \\
& a_4 = a_3 + d  =  a_1 + 3d \\
& ... \\
& \boxed{
a_n = a_1 + (n-1) d
}
\end{align}

方法2: 叠加法:

\begin{align}
已知:
& a_2 - a_1 = d <- 第1个d, 即与后一项的系数相同 \\
& a_3 - a_2 = d <- 第2个d\\
& a_4 - a_3 = d <- 第3个d\\
& ... \\
& a_n - a_{n-1} = d <- 第 n-1 个d\\
& 把上面所有式子, 等号左边全加起来, 等号右边也全加起来, 就是: \\
& (- a_1 + a_2) + (- a_2 + a_3 ) + (- a_3 + a_4 ) + ... + (- a_{n-1} + a_n) = d+d+d+...+d \\
& -a_1  + a_n = (n-1)d \\
即: & \boxed{
 a_n = a_1 +(n-1)d
}
\end{align}


.标题
====
例如：求 10, 5, 0, -5 的通项公式.

思考: 使用等差数列的通项公式即可. 可知:
\begin{align}
& a_1 = 10 \\
& 公差d = 5-10 =-5
\end{align}

代入等差数列的通项公式 :
\begin{align}
a_n & =  a_1 +(n-1)d \\
& = 10  +(n-1)(-5) \\
& = 10 -5n +5 = -5n + 15
\end{align}
====

.标题
====
例如： 等差数列 8, 5, 2, ... 的第20项是多少?

\begin{align}
& 可知: \\
& a_1 = 8, \\
& d = 5-8 = -3 \\
& 所以代入等差数列的通项公式 : a_n  =  a_1 +(n-1)d \\
& a_n = 8 -3(n-1) <-这就是本等差数列的通项公式 \\
& a_{20} = 8-3(20-1) = 8 - 3*19 = -49 <- 第20项的值
\end{align}
====

.标题
====
例如：问: -401 是不是 等差数列 -5, -9, -13, ... 中的项?

我们用方程来做一做就能知道.

先算出该等差数列的通项公式:
\begin{align}
& a_1 = -5 \\
& d = -9 -(-5) = -4 \\
& 代入差数列的通项公式  a_n  =  a_1 +(n-1)d \\
& a_n = -5 -4(n-1) <- 即本例等差数列的通项公式
\end{align}

把 -401 代入上面的通项公式中, 只要 n 是整数(项的序数不存在分数的), 就说明 -401 的确是本等差数列中的项.

\begin{align}
& -401 = -5 -4(n-1) \\
& n = 100 <- 的确是整数, 说明 -401是本等差数列中的第100项
\end{align}

所以 -401 是本等差数列中的项.
====





---






---

https://www.bilibili.com/video/BV1bE411T7cA?p=148

5:32
