
= partial 类
:sectnums:
:toclevels: 3
:toc: left

---

== partial 类

*Partial是局部类型的意思。允许我们将一个类、结构或接口分成几个部分，分别实现在几个不同的.cs文件中。C#编译器在编译的时候, 仍会将各个部分的局部类型, 合并成一个完整的类.*

适用情况：

(1) 类型特别大，不宜放在一个文件中实现。
(2) **一个类型中的一部分代码, 为自动化工具生成的代码，不宜与我们自己编写的代码混合在一起。**winfom 等
(3) 需要多人合作编写一个类。

2. 局部类型的限制

(1) *局部类型, 只适用于类、接口、结构，不支持委托和枚举。*
(2) *同一个类型的各个部分, 必须都有修饰符 partial。*
(3) *使用局部类型时，一个类型的各个部分, 必须位于相同的命名空间中。*
(4) 一个类型的各个部分, 必须被同时编译。

3. 局部类型的注意点

(1) **关键字partial是一个上下文关键字，只有和 class、struct、interface 放在一起时才有关键字的含义。**因此partial的引入, 不会影响现有代码中名称为partial的变量。
(2) *局部类型的各个部分, 一般是分开放在几个不同的.cs文件中，但C#编译器允许我们将他们放在同一文件中。*

4. 局部类型的应用特性

*在局部类型上的特性, 具有“累加”效应。*

[Attribute1, Attribute2("Hello")]
partial class Class1{}

[Attribute3, Attribute2("Exit")]
partial class Class1{}


相当于

[Attribute1, Attribute2("Hello"), Attribute3, Attribute2("Exit")]
class Class1 {}


注：Attribute2属性允许在类上多次使用。

5. 局部类型上的修饰符

(1) 一个类型的各个部分上的访问修饰符, 必须维持一致性。
(2) *如果一个类型有一个部分使用了abstract修饰符，那么整个类都将被视为抽象类。*
(3) *如果一个类型有一个部分使用了 sealed 修饰符，那么整个类都将被视为密封类。*
(4) **一个类的各个部分, 不能使用相互矛盾的修饰符，**比如不能在一个部分上使用abstract，又在另一个部分上使用sealed。

6. 局部类型的基类和接口

(1) *一个类型的各个部分上指定的基类必须一致。某个部分可以不指定基类，但如果指定，则必须相同。*
(2) *局部类型上的接口具有“累加”效应。*

partial class Class2: Iinterface1, Iinterface2 {}
partial class Class2: Iinterface3 {}
partial class Class2: Iinterface2 {}


相当于

class Class2: Iinterface1, Iinterface2, Iinterface3 {}


下面的文件中, 有两个同名的部分类, 它们最终会合成一个类.
[,subs=+quotes]
----
namespace ConsoleApp4 {
    *internal partial class Cls我的部分类 {*
        public string name;
        public int id;

        public Cls我的部分类(string name, int id) {
            this.name = name;
            this.id = id;
        }
    }


    *internal partial class Cls我的部分类 {*
        public void fnPrint() {
            Console.WriteLine("{0},{1}",this.name, this.id);
        }
    }
}
----

主文件中:
[,subs=+quotes]
----
namespace ConsoleApp4 {
    internal class Program {


        static void Main(string[] args) {
            *Cls我的部分类 ins我的部分类 = new Cls我的部分类("zrx", 19);*

            ins我的部分类.fnPrint(); //zrx,19

        }
    }
}
----


'''




