
= three kingdom
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


我想创建一个类似光荣三国志的小游戏, 虽然游戏背景是古代的, 但我想用现代经济学理论来操作, 我想要带入一套经济模拟系统, 即"系统动力学模型", 来模拟国家内经济, 与国际间经济的运行. 一国的经济相关参数需要包括:
- 利率
- 税率
- GDP增长率,
- GDP值,
- 人均GDP
- 人均收入
- 人均可支配收入
- 就业率,
- 失业率,
- 通货膨胀率,
- CPI,
- PPI
- 贸易顺差率(计算公式为：贸易顺差率 = （出口总额 - 进口总额） / （出口总额 + 进口总额）× 100% ),
- 贸易逆差率 (计算公式为: 贸易逆差率 =（进口总额 - 出口总额） / （出口总额 + 进口总额）× 100%)
- 一国人口年龄结构 (即各年龄段占一国总人口的比率)
- 老龄化比率
- 军费占GDP的百分比
- 军队占总人口的比率

这是我能想到的一些必备参数, 如果你还有其它重要的参数补充, 请补充进来.

这些参数之间, 会彼此影响, 就能建立起一个"系统动力学模型".
比如: 利率的高低, 失业率, 通胀率, 老龄化, 都会影响GDP增长率.
老龄化太高, 税率太高, 会导致经济崩溃, GDP停滞甚至负增长.
GDP增长率, 又会影响人均收入, 和人均可支配收入.
军费占GDP的百分比越高, 会影响GDP增长率,
等等

请你用上面的这些参数, 包括你觉得还需要补充进来的参数 (如果有的话), 结合现代国家运行理论, 来建立起一个系统动力学模型, 并给出具体且合理的百分比变化率.  可以用在游戏中, 来模拟各国国内的经济运行, 和国家间的经济贸易.

给出python代码, 并详细解释每句代码实现的功能






----------------



我想用Python来编写一个类似光荣三国志的小游戏，内容如下：

游戏有以下几个数据库(可用表格表示)：

1.人才数据库. 表头中的内容包括:
- 姓名
- 政治能力(数值范围1-10, 该数值决定发展国内经济时的效率)
- 统帅能力(数值范围1-10, 该数值决定了是否有能力独立带兵打仗. 比如关羽有能力独立带兵打仗, 但荀彧就不行了, 荀彧更偏向搞内政, 发展经济. 诸葛亮和曹操则是全才, 既能发展经济,搞内政,又能独立带兵打仗.)
- 所属政治势力(即君主的名字, 任何人都可以成为君主)
- 官职 (可选项包括:君主, 丞相, 财政部长, 国防部长, 外交部长, 郡太守, 郡财政部长, 郡国防部长. 这里面的每个官职,都会对应不同的权限. 权限这块, 会在"官职数据库"中做规定.)

例子如下:
姓名 | 政治能力 | 统帅能力 | 所属政治势力 | 官职
曹操 | 10 | 10 | 曹操 |  君主
荀彧 | 9 | 3 | 曹操 |  财政部长
诸葛亮 | 10 | 10 | 刘备 | 丞相
刘备 | 9 | 5 | 刘备 | 君主
周瑜 | 8 | 8 | 孙策 | 国防部长
关羽 | 5 | 8 | 刘备 | 郡国防部长
庞统 | 8 | 8 | 刘备 | 财政部长


2.官职数据库, 表中的内容例子如下 (数字1代表有这个权限, 数字0代表无此权限):
官职名 | 人事权 | 财权 | 军权 | 外交权
君主 | 1 | 1 | 1 | 1
丞相 | 1 | 1 | 1 | 1
财政部长 | 0 | 1 | 0 | 0
国防部长 | 0 | 0 | 1 | 1
外交部长 | 0 | 0 | 0 | 1
郡太守 | 1 | 1 | 1 | 1
郡财政部长 | 0 | 1 | 0 | 0
郡国防部长 | 0 | 0 | 1 | 0

各权力的说明:
拥有"人事权"的权限, 即能够自主任免下属官员. 如, 郡太守拥有"人事权",他就有权利能自主任免自己的两个属下: 郡财政部长, 和郡国防部长.
拥有"财权"的权限, 即能够给人发工资, 在本游戏中就意味着能够招募士兵
拥有"军权"的权限, 即能够发动战争, 去攻占敌人城市, 或在敌人来袭击时, 进行出战.
拥有"外交权"的权限, 即能够执行外交动作, 如结盟, 毁约, 或商定共同讨伐某个敌人.




3.城市数据库, 表中的内容例子如下:
城市名字 | 所属势力 | 太守 | 郡财政部长 | 郡国防部长 | 工商业能力 | 年GDP值 | 人口数 | 军队人数
长安 | 曹操 | 曹洪 | None | None |

说明:
表中的None, 表示还未赋值. 由玩家在游戏中来指定.
工商业能力, 数值的计算公式是 =
年GDP值, 数值的计算公式是 =
军队人数, 计算公式是 =

GDP/年（由工商业能力，非军人口，加权得到）
- 军队数（由占人口百分比算出，军队数越多，影响工商业能力下降越多）




4."交通网络"数据库


5."国家统计数据"数据库, 表中的内容例子如下:


税率 =



城市类，有以下属性（没有方法，方法全部归由人才去做，因为事在人为）：
- 城市名字
- 所属势力
- 太守
- 郡财政部长
- 郡国防部长
- 人口数
- 工商业能力
- GDP/年（由工商业能力，非军人口，加权得到）
- 军队数（由占人口百分比算出，军队数越多，影响工商业能力下降越多）

人物类，有以下属性和方法：
- 姓名
- 政治能力（影响发展经济）
- 领导能力（影响军事）
- fn提案（）
- 所属政治势力
-

政府系统类（政治势力）：
- 君主
- 丞相总理
- 中央财政部长
- 中央国防部长
- fn人事任免
- fn修改政策
- fn做事
- fn执行军事行动
- fn下一回合（每月一开始，会自动所有中央高官和太守提案，汇报工作）

交通网络系统类


战争系统类
- fn判断双方胜负
- fn战后影响执行（交战城市工业能力下降，人口逃亡，到周边城市，GDP越高者，逃入的难民比例越多）





游戏流程为：
1.打开游戏后，显示菜单，让玩家选择要扮演的君主角色，包括3个：曹操，刘备，孙权。

2.玩家选定角色后，就进入“指令界面”，有以下菜单可选择：
2-1，“人事任免”
2-2，“指定新政策目标”
2-3，“执行军事行动”
2-4，“下一回合”
2-5，“保存与退出游戏”

其中，
3.