
= python logging模块
:toc:

---

== 第一个例子

[source, python]
....
import logging

# 全局配置
logging.basicConfig(filename="test.log",  # 日志输出到文件的文件名
                    filemode="a+",  # 文件模式，r[+]、w[+]、a[+]
                    format="%(asctime)s %(name)s:%(levelname)s:%(message)s",  # 日志输出的格式
                    datefmt="%d-%M-%Y %H:%M:%S",  # 日志附带日期时间的格式
                    level=logging.DEBUG,  # 设置日志输出级别
                    )

logging.warning('warning msg...') # 14-55-2019 12:55:25 root:WARNING:warning msg...
....

format参数中的部分子参数如下:


|===
|功能 |写法

|打印日志的时间
|%(asctime)s

|打印当前执行的程序名(即py文件名)
|%(filename)s

|打印日志信息
|%(message)s

|打印日志的级别
|%(levelname)s


|所有参数见
|https://docs.python.org/3/library/logging.html?highlight=logging%20threadname#logrecord-attributes
|===

[source, python]
....
import logging

logging.basicConfig(format="时间 %(asctime)s "
                           " /程序文件 %(filename)s"
                           " /日志级别 %(levelname)s"
                           " /信息 %(message)s",
                    datefmt="%d-%M-%Y %H:%M:%S",  # 日志附带日期时间的格式
                    level=logging.WARNING,  # 设置日志输出级别
                    )

str = 'zzr'
logging.warning(str)
# 时间 14-10-2019 13:10:15  /程序文件 py001.py /日志级别 WARNING /信息 zzr
....

---

==== 在异常发生时, 如何也把log保存下来?

当发生异常时，直接使用无参数的 debug()、info()、warning()、error()、critical() 方法并不能记录异常信息，有三种解决方法:

[source, python]
....
import logging

logging.basicConfig(filename="test.log",  # 日志输出到文件的文件名
                    filemode="a+",  # 文件模式，r[+]、w[+]、a[+]
                    format="%(asctime)s %(name)s:%(levelname)s:%(message)s",  # 日志输出的格式
                    datefmt="%d-%M-%Y %H:%M:%S",  # 日志附带日期时间的格式
                    level=logging.DEBUG,  # 设置日志输出级别
                    )

a = 5
b = 0

try:
    c = a / b
except Exception as e:
    # 下面三种方式都能解决, 推荐使用第一种
    # 方法1: 使用 exception() 方法
    logging.exception("Exception occurred")

    # 方法2: 设置 exc_info 参数为 True
    logging.error("Exception occurred", exc_info=True)

    # 方法3: 使用 log() 方法，但还要设置日志级别和 exc_info 参数。
    logging.log(level=logging.DEBUG, msg="Exception occurred", exc_info=True)
....

---

== 日志等级 Level

logging 模块共提供了如下等级，每个等级其实都对应了一个数值


|===
|等级|数值
|CRITICAL|50
|FATAL|50
|ERROR|40
|WARNING|30
|WARN(就是WARNING的简写)|30
|INFO|20
|DEBUG|10
|NOTSET|0

|===

如果我们设置了输出 level，系统便只会输出 level 数值大于或等于该 level 的的日志结果.
[source, python]
....
logger = logging.getLogger(__name__)
logger.setLevel(level=logging.WARN) # 设置level
....

---

== Logger 对象

一个系统只有一个 Logger 对象，并且该对象不能被直接实例化，没错，这里用到了单例模式. +
获取 Logger 对象的方法为 getLogger()。

注意：这里的单例模式并不是说只有一个 Logger 对象，而是指整个系统只有一个根 Logger 对象，Logger 对象在执行 info()、error() 等方法时实际上调用都是根 Logger 对象对应的 info()、error() 等方法。

我们可以创造多个 Logger 对象，但是真正输出日志的是根 Logger 对象。每个 Logger 对象都可以设置一个名字.


---
